In [ ]:
#program 1: Calculate total weekly energy from a list
daily_kwh = [400, 850, 500, 300, 600, 700, 450, 560, 780, 690 ]
total_energy = sum(daily_kwh)
print("Total Energy Used:", total_energy, "kwh")

Total Energy Used: 5830 kwh

In [ ]:
#program 2: store building usage data
building_usage = {
    "CSE": 400,
    "HOSTEL": 300
}
print("Hostel used:", building_usage["HOSTEL"], "kwh")

Hostel used: 300 kwh

In [1]:
#program 3:A function to calculate electricity cost
def calculate_bill(kwh, rate_per_unit):
    return kwh * rate_per_unit
todays_bill = calculate_bill(850, 8)
print("Today's estimated bill is Rs.", todays_bill)

Today's estimated bill is Rs. 6800

In [4]:
#program 4: Read a file line by line
with open("campus_energy.csv", "r") as file:
  for line in file.readlines():
    print(line.strip())

﻿DATE,Building,kwh-used,Peak-Hour-usage
05-10-2026,CSE,400,120
06-10-2026,ECE,850,230
07-10-2026,CIVIL,500,340
08-10-2026,HOSTEL,300,555
09-10-2026,MECH,600,245
10-10-2026,CSE,700,645
11-10-2026,ECE,450,578
12-10-2026,CIVIL,560,278
13-10-2026,HOSTEL,780,124
14-10-2026,MECH,690,11

In [7]:
#import the pandas library
import pandas as pd

#Load the dataset you created
df = pd.read_csv('campus_energy.csv')

#Display the first few rows of the data
print("Here is the raw data:")
display(df.head())

#Group the data to see total usage per building
building_totals = df.groupby('Building')['kwh-used'].sum()
print("\nTotal usage per building:")
print(building_totals)

#Generate a statistical summary (average, min, max) of the numeric columns
print("\nStatistical Summary:")
display(df.describe())

Here is the raw data:

         DATE Building  kwh-used  Peak-Hour-usage
0  05-10-2026      CSE       400              120
1  06-10-2026      ECE       850              230
2  07-10-2026    CIVIL       500              340
3  08-10-2026   HOSTEL       300              555
4  09-10-2026     MECH       600              245

Total usage per building:
Building
CIVIL     1060
CSE       1100
ECE       1300
HOSTEL    1080
MECH      1290
Name: kwh-used, dtype: int64

Statistical Summary:

         kwh-used  Peak-Hour-usage
count   10.000000        10.000000
mean   583.000000       312.600000
std    174.550216       215.162058
min    300.000000        11.000000
25%    462.500000       150.500000
50%    580.000000       261.500000
75%    697.500000       501.250000
max    850.000000       645.000000

In [8]:
#Create the README.md file and write a message inside it
with open("README.md", "w") as file:
  file.write("#Smart Campus Energy Project\n")
  file.write("This repository contains my week 1 hands-on Python and pandas assignment.\n")
  file.write("Created by: [Nandini]")
print("README.md has been successfully created")

README.md has been successfully created